import FloatingText from "./FloatingText";
import SignUp from "./SignUp";
import AnimatedImage from "./AnimatedImage";
import ImageViewer from "./ImageViewer";
import MobSignup from "./MobSignup";
import Login from "./Login";
import SignUpFloat from "./SignUpFloat";
import Sidebar from "./SideBar";
import TopNavBar from "./TopNavBar";
import SearchBar from "./SearchBar";
import TextInput from "./TextInput";
import Loading from "./Loading";
import CategorySlider from "./CategorySlider";
import PostCard from "./PostCard";
import PopUp from "./PopUp";
import SavedRecp from "./SavedRecp";
import MobNav from "./MobNav";
import GoogleSignIn from './GoogleSignIn'
import Spinner from "./Spinner";
import FollowButton from "./FollowButton";
import ErrorComponent from "./ErrorComponent";
import RenderImages from "./RenderImages";
import EditProfile from "./EditProfile";
export{ FloatingText, Loading, MobSignup,RenderImages, SignUp, ErrorComponent, EditProfile, AnimatedImage, ImageViewer, Login, SignUpFloat, FollowButton, SearchBar,  GoogleSignIn, TopNavBar, Sidebar, TextInput, CategorySlider, PostCard,Spinner, PopUp, SavedRecp, MobNav}